# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(b0f53ad6-7dd8-4b1d-ba55-234f90a2a54c)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az appservice plan create -g tfrg -n myasp --is-linux --number-of-workers 1 --sku F1'
    
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(b0f53ad6-7dd8-4b1d-ba55-234f90a2a54c)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az webapp create -g tfrg -p myasp -n mywebapp-ur123 \
        --runtime "java|11|Java SE|8"